development:
  adapter: postgresql
  database: salsa_dev
  username:
  password:
  host: localhost

test: &TEST
  adapter: postgresql
  database: salsa_test
  username:
  password:
  host: localhost
  min_messages: warning

production:
  adapter: postgresql
  database: salsa_prod
  username:
  password:
  host: localhost

cucumber:
  <<: *TEST
